### ISSUE TITLE
copy.deepcopy() error in FLORIS object instantiation using Python 3.6

### ISSUE THREAD

**Issue by NilsGaukroger** [NREL/floris#119]
**Bug description**
Instantiating the FLORIS object using fi = wfct.floris_interface.FlorisInterface("input.json") gives an error using copy.deepcopy() in floris/floris/simulation/farm.py, "TypeError: can't pickle _thread.Rlock objects"

**To Reproduce**
<Update the following list with your specific information.>
1. Initialise the floris interface, fi, using, for example, example_00_open_and_vis_floris.py using Python 3.6.8 - or perhaps any Python 3.6 release, I have only tried with 3.6.8
2. Open output
3. See the error

**Screenshots, if applicable**
```
Traceback (most recent call last):
  File "model.py", line 44, in <module>
    fi = wfct.floris_interface.FlorisInterface("input.json")
  File "/ddn/home/npcl74/floris/floris/tools/floris_interface.py", line 64, in __init__
    self.floris = Floris(input_file=input_file, input_dict=input_dict)
  File "/ddn/home/npcl74/floris/floris/simulation/floris.py", line 53, in __init__
    self.farm = Farm(farm_dict, turbine, wake)
  File "/ddn/home/npcl74/floris/floris/simulation/farm.py", line 90, in __init__
    [copy.deepcopy(turbine) for ii in range(len(layout_x))]),
  File "/ddn/home/npcl74/floris/floris/simulation/farm.py", line 90, in <listcomp>
    [copy.deepcopy(turbine) for ii in range(len(layout_x))]),
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cluster-Apps/python/3.6.8/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
```

**Floris Version**
Using version 2.0.1 from develop branch

**System Information (please complete the following information):** 
 - OS: HPC Linux Cluster
 - Library versions
   * matplotlib 3.0.2
   * numpy 1.16.1
   * pytest 5.3.5
   * scipy 1.2.1

**Additional context**
Running on HPC service. Also received warning about a call a "fork()" system call to create a child process. This is a warning I have received previously when running this serial script on this HPC service, but it is a warning I have received when running a parallel script. The warning is:

```
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[24480,1],0] (PID 11849)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
```

Apologies for any discrepancies with this bug report, it's my first.

**Comment by rqwang** [comment]
Found the same bug when I run floris in the google colab. From a quick search, this problem may be due to python 3.6, because it didn't happen to my laptop which runs on 3.7

**Comment by rafmudaf** [comment]
Hi @NilsGaukroger - This issue was due to how we were using the `logging` module. It was fixed in the `develop` branch in #123 and will be included in the next release, v2.1.0.

Until then, please verify that the develop branch works on your system.
