### ISSUE TITLE
Bug report: Yaw optimization with uncertainty raises a type error

### ISSUE THREAD

**Issue by Josue9740** [NREL/floris#228]
**Bug description**
Yaw optimization raises a TypeErrror ("loop of ufunc does not support argument 0 of type float which has no callable sin method") when uncertainty is introduced in the simulation. 

**To Reproduce**
The best way to see this bug is running the example file "optimize_yaw_wind_rose_robust.py", which can be found in: "floris/examples/optimization/scipy/controls_optimization/". In this example, yaw optimization is conducted with and without uncertainty. The model works perfectly for the case without uncertainty, but raises the error described below when introducing uncertainty in the model. 

1. Run "optimize_yaw_wind_rose_robust.py"
3. See the error: 

AttributeError: 'float' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-7-14855074c561>", line 1, in <module>
    df_opt_unc = yaw_opt.optimize()

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\floris\tools\optimization\scipy\yaw_wind_rose.py", line 736, in optimize
    unc_options=self.unc_options,

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\floris\tools\floris_interface.py", line 1048, in get_turbine_power
    self.reinitialize_flow_field(wind_direction=wd_orig + delta_wd)

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\floris\tools\floris_interface.py", line 256, in reinitialize_flow_field
    wind_map=self.floris.farm.wind_map,

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\floris\simulation\flow_field.py", line 524, in reinitialize_flow_field
    self.set_bounds(bounds_to_set=bounds_to_set)

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\floris\simulation\flow_field.py", line 418, in set_bounds
    / np.pi

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\scipy\stats\morestats.py", line 3338, in circmean
    nan_policy=nan_policy)

  File "C:\Users\.conda\envs\wisdem-env\lib\site-packages\scipy\stats\morestats.py", line 3285, in _circfuncs_common
    sin_samp = sin((samples - low)*2.*pi / (high - low))

TypeError: loop of ufunc does not support argument 0 of type float which has no callable sin method

**Expected behavior**
The example should resolve the optimization without errors.

**Floris Version**
Floris: 2.3.

**System Information (please complete the following information):** 
 - OS: Windows 10 64 bits
 - Library versions
   * numpy 1.21.0
   * scipy 1.6.3.
   * pandas 1.2.5.

**Comment by Bartdoekemeijer** [comment]
Hi Josue,

I believe this is the same issue as #205. It seems that @bayc has fixed this in the `develop` branch (see #208). Hence, try switching to the `develop` branch or alternatively downgrade your `numpy` version to 1.19.5 using `pip install numpy==1.19.5`.

**Comment by bayc** [comment]
@Josue9740 Bart was right, we had a fix for this in develop, and that was just merged into main, so you should be able to pull down the new code and this problem should go away. Going to close this now but let us know if you still have an issue.
