### ISSUE TITLE
Error installing FLORIS: No module named 'distutils.cmd'

### ISSUE THREAD

**Issue by matheusseidel** [NREL/floris#589]
Hello,

I'm new to FLORIS and I tried installing it on WSL, Linux Ubunto subsystem on Windows 11.

I tried installing by running `pip install floris`, but I got the fallowing error:

```
mbseidel@Matheus-Seidel:~$ pip install floris
Traceback (most recent call last):
  File "/home/mbseidel/.local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/home/mbseidel/.local/lib/python3.8/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

I'd appreciate any help with this problem.

**Comment by paulf81** [comment]
I would recommend installing this within a virtual environment such as conda, I believe that will resolve the issue

**Comment by paulf81** [comment]
There’s also some additional install Instructions here: https://github.com/NREL/floris

**Comment by rafmudaf** [comment]
This looks like an issue with your installation of pip itself rather than an issue with floris. See this thread: https://github.com/pypa/get-pip/issues/124

**Comment by matheusseidel** [comment]
Ok. Thanks.
