### ISSUE TITLE
Dependency issue when installing docs extras with Python 3.11

### ISSUE THREAD

**Issue by acse-xm421** [NREL/floris#691]
# Examples broken after installing docs dependencies with Python 3.11

## How to reproduce

Clone and install floris. 
```pip install -e ".[develop, docs]"```.
And then run example_01
```python examples/01_opening_floris_computing_power.py```
It will fail.
But it works well if I use ```python 3.10``` rather than ```python 3.11```, or only install "develop" without "docs" extras.```pip install -e ".[develop]```.
## Relevant output

```
/home/mm/miniconda3/envs/floris_2/lib/python3.11/site-packages/attr/_make.py:918: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
FlorisInterface...(This is the line added to test the change source code)
Traceback (most recent call last):
  File "/home/mm/acse_projects/wind-farm/floris/examples/01_opening_floris_computing_power.py", line 33, in <module>
    fi = FlorisInterface("examples/inputs/gch.yaml")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/wind-farm/floris/floris/tools/floris_interface.py", line 58, in __init__
    self.floris = Floris.from_file(self.configuration)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/wind-farm/floris/floris/simulation/floris.py", line 338, in from_file
    return Floris.from_dict(input_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/wind-farm/floris/floris/type_dec.py", line 160, in from_dict
    return cls(**kwargs)
           ^^^^^^^^^^^^^
  File "<attrs generated init floris.simulation.floris.Floris>", line 11, in __init__
  File "/home/xx/wind-farm/floris/floris/simulation/floris.py", line 104, in __attrs_post_init__
    self.grid = TurbineGrid(
                ^^^^^^^^^^^^
  File "<attrs generated init floris.simulation.grid.TurbineGrid>", line 15, in __init__
  File "/home/xx/wind-farm/floris/floris/simulation/grid.py", line 161, in __attrs_post_init__
    super().__attrs_post_init__()
    ^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
```
## Floris version

FLORIS 3.4
## System Information

 - Python version: 3.11
 ## Discussion Link
https://github.com/NREL/floris/discussions/689#discussioncomment-6597441

**Comment by rafmudaf** [comment]
Given no response to a request for more information (see https://github.com/NREL/floris/discussions/689#discussioncomment-7589259), I'll consider this issue resolved by using updated versions of dependencies.
